version: '3'
services:
  node1:
    build: .
    stdin_open: true
    tty: true
    environment:
      - IP=172.19.0.2
      - PORT=8000
      - BOOTSTRAP=True
      - IP_BOOTSTRAP=172.19.02
      - PORT_BOOTSTRAP=8000
      - NODES=5
      - CAPACITY=2
    networks:
      - blockchat

  node2:
    build: .
    stdin_open: true
    tty: true
    environment:
      - IP=172.19.0.3
      - PORT=8001
      - BOOTSTRAP=False
      - IP_BOOTSTRAP=172.19.0.2
      - PORT_BOOTSTRAP=8000
      - NODES=5
      - CAPACITY=2
    networks:
      - blockchat

  node3:
    build: .
    stdin_open: true
    tty: true
    environment:
      - IP=172.19.0.4
      - PORT=8002
      - BOOTSTRAP=False
      - IP_BOOTSTRAP=172.19.0.2
      - PORT_BOOTSTRAP=8000
      - NODES=5
      - CAPACITY=2
    networks:
      - blockchat

  node4:
    build: .
    stdin_open: true
    tty: true
    environment:
      - IP=172.19.0.5
      - PORT=8003
      - BOOTSTRAP=False
      - IP_BOOTSTRAP=172.19.0.2
      - PORT_BOOTSTRAP=8000
      - NODES=5
      - CAPACITY=2
    networks:
      - blockchat

  node5:
    build: .
    stdin_open: true
    tty: true
    environment:
      - IP=172.19.0.6
      - PORT=8004
      - BOOTSTRAP=False
      - IP_BOOTSTRAP=172.19.0.2
      - PORT_BOOTSTRAP=8000
      - NODES=5
      - CAPACITY=2
    networks:
      - blockchat

networks:
  blockchat: