# version: '3.7'

# services:
#   node1:
#     build: .
#     ports:
#       - "5001:6789"
#     environment:
#       - NODE_ID=1
#     networks:
#       - blockchain_network

#   node2:
#     build: .
#     ports:
#       - "5002:6789"
#     environment:
#       - NODE_ID=2
#     networks:
#       - blockchain_network

#   node3:
#     build: .
#     ports:
#       - "5003:6789"
#     environment:
#       - NODE_ID=3
#     networks:
#       - blockchain_network

#   node4:
#     build: .
#     ports:
#       - "5004:6789"
#     environment:
#       - NODE_ID=4
#     networks:
#       - blockchain_network

#   node5:
#     build: .
#     ports:
#       - "5005:6789"
#     environment:
#       - NODE_ID=5
#     networks:
#       - blockchain_network

# networks:
#   blockchain_network:
#     driver: bridge
